### ISSUE TITLE
Problem when installing with composer require

### ISSUE THREAD

**Issue by rodde177** [bitbull-team/magento2-module-instagramwidget#4]
**Preconditions**
Magento version: 2.1.2
composer require command

Right now the module composer.json has dependency on older version of magento/framework, v. `"100.0.*"`, while the current version is at `"100.1.2"` (M2 version 2.1.2).
My suggestion, depending on which version you want to support, is to use hyphen, caret or tilde before version number. Or just use `"*"` to disregard version number.
Here is documentation for versioning: [https://getcomposer.org/doc/articles/versions.md](https://getcomposer.org/doc/articles/versions.md)

![skarmavbild 2016-11-23 kl 14 14 57](https://cloud.githubusercontent.com/assets/455527/20563452/fd3b5afe-b188-11e6-9bf2-18a7a7cdfb6b.png)

**Comment by lorenaramonda** [comment]
Removed magento module requirements since version 4.0, so this solves the issue.
